---
- name: create a user with ssh access
  hosts: target1
  become:
  tasks:
    - name: create devuser
      ansible.builtin.user:
        name: devuser
        shell: /bin/bash
        create_home: yes

    - name: Create .ssh directory
      ansible.builtin.file:
        path: /home/devuser/.ssh
        state: directory
        owner: devuser
        group: devuser
        mode:  0700

    - name: Add authorized key
      ansible.builtin.copy:
        content: ssh-rsa AAAAB3Nz...  
        dest: /home/devuser/.ssh/authorized_keys
        owner: devuser
        group: devuser
        mode:  0600
